version: '3.8'
services:
  frontend:
    build: .
    ports:
      - 3000:3000
    container_name: frontend
    network_mode: host

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=gowpet-pos
  #   container_name: db
  #   network_mode: host

  backend:
    build: https://github.com/jonfelixrico/gowpet-pos-backend.git#dockerfile-test
    ports:
      - 3005:3005
    # depends_on:
    #   - postgres
    container_name: backend
    network_mode: host

  cypress:
    build:
      dockerfile: ./docker/cypress/Dockerfile
    command: dockerize -wait http://localhost:3005/authenticate/publicKey -wait http://localhost:3000 && pnpm test:e2e:ci
    network_mode: host
    working_dir: /app
