version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    container_name: frontend
    network_mode: host

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=gowpet-pos
  #   container_name: db
  #   network_mode: host

  backend:
    build: https://github.com/jonfelixrico/gowpet-pos-backend.git#dockerfile-test
    ports:
      - 3005:3005
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres/gowpet-pos
    # depends_on:
    #   - postgres
    container_name: backend
    network_mode: host

  cypress:
    image: cypress:latest
    profiles:
      - cypress
    depends_on:
      - frontend
      - backend
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://localhost:3000
    command: 'npx cypress run'
    ipc: host
    build: ./services/cypress
    ports:
      - '9000:80'
    volumes:
      - './cypress/e2e:/app/tests:ro'
