import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { ReactNode } from 'react'
import { OffscreenContainerProvider } from '@/contexts/OffscreenContainerContext'
import { EnvScript } from 'next-runtime-env'
import { unstable_noStore as noStore } from 'next/cache'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  noStore() // Opt into dynamic rendering

  return (
    <html lang="en">
      <head>
        <EnvScript
          env={{
            BACKEND_URL: process.env.BACKEND_URL,
          }}
        />
      </head>

      <body className={inter.className}>
        <Providers>
          <OffscreenContainerProvider>{children}</OffscreenContainerProvider>
        </Providers>
      </body>
    </html>
  )
}
