import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { ReactNode } from 'react'
import { OffscreenContainerProvider } from '@/contexts/OffscreenContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <OffscreenContainerProvider>{children}</OffscreenContainerProvider>
        </Providers>
      </body>
    </html>
  )
}
