version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gowpet-pos

  backend:
    image: ${E2E_BACKEND_IMAGE:-ghcr.io/jonfelixrico/gowpet-pos-backend:develop}
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gowpet-pos
    depends_on:
      - db
    ports:
      - 3005:3005
