name: Prepare PNPM

runs:
  using: composite
  steps:
    - name: Set up next.js build cache
      uses: actions/cache@v3
      with:
        path: .next/cache
        key: next-build-${{ github.sha }}
        restore-keys: next-build-${{ github.sha }}
