name: Prepare PNPM

outputs:
  cache-hit:
    description: 'Boolean that indicates if the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Set up next.js build cache
      uses: actions/cache@v3
      with:
        path: .next
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ github.sha }}
      id: cache
