version: '3.8'
services:
  frontend:
    build:
      dockerfile: ./Dockerfile
    container_name: frontend

  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gowpet-pos
    container_name: db

  backend:
    build: https://github.com/jonfelixrico/gowpet-pos-backend.git#develop
    depends_on:
      - postgres
    container_name: backend
    environment:
      - spring.datasource.url=jdbc://postgresql://postgres/gowpet-pos

  cypress:
    build:
      dockerfile: ./docker/cypress/Dockerfile
    command: |
      dockerize -wait http://backend:3005/authenticate/publicKey -wait http://frontend:3000 -timeout 30s
      pnpm test:e2e:ci
    working_dir: /app
    environment:
      - CYPRESS_BASE_URL=http://nginx
