version: '3.8'
services:
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ../..
    container_name: frontend

  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gowpet-pos
    container_name: db

  backend:
    build: https://github.com/jonfelixrico/gowpet-pos-backend.git#develop
    depends_on:
      - postgres
    container_name: backend
    environment:
      - spring.datasource.url=jdbc://postgresql://postgres/gowpet-pos

  cypress:
    build:
      dockerfile: ../cypress/Dockerfile
      context: ../..

    # Steps involved:
    # 1. Make sure that FE and BE are up
    # 2. Create test user
    # 3. Execut the test
    command: |
      dockerize -wait http://backend:3005/authenticate/publicKey -wait http://frontend:3000 -timeout 30s
      curl -XPOST -H "Content-type: application/json" -d '{ "username": "root", "password": "password" }' 'http://backend:3005'
      pnpm test:e2e:ci
    working_dir: /app
    environment:
      - CYPRESS_BASE_URL=http://nginx
