version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gowpet-pos

  backend:
    image: ghcr.io/jonfelixrico/gowpet-pos-backend
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gowpet-pos
      - APP_DEBUG=true
    depends_on:
      - db

  frontend:
    image: ghcr.io/jonfelixrico/gowpet-pos-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - 3000:3000
