name: PR Workflow

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - 'develop'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Check if it builds
        shell: bash
        run: pnpm build

  test-component:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Run Cypress component testing
        uses: cypress-io/github-action@v6
        with:
          component: true

  test-e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      # From https://stackoverflow.com/a/67290085
      - name: Convert slashes to dashes
        run: |
          BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}
          DB_NAME="${BRANCH_NAME/"\//\-}"
          echo "converted=$DB_NAME" >> $GITHUB_OUTPUT
        id: convert

      - name: Test
        run: echo ${{ steps.convert.outputs.converted }}

      - name: Run e2e tests
        shell: bash
        run: pnpm test:e2e:ci
        env:
          E2E_BACKEND_IMAGE: ghcr.io/jonfelixrico/gowpet-pos-backend:${{ github.ref_name }}
