name: PR Workflow

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Check if it builds
        shell: bash
        run: pnpm build

  test-component:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Run Cypress component testing
        uses: cypress-io/github-action@v6
        with:
          component: true

  test-e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Run e2e tests
        shell: bash
        run: pnpm test:e2e:ci
