name: Run E2E tests

on:
  workflow_call:

jobs:
  test-e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: ./.github/actions/prepare-pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile

      - name: Run e2e tests
        shell: bash
        run: pnpm test:e2e:ci
